"""
Event-Driven Backtester Components

Holds the event loop and generic abstract base classes for
DataHandlers, Strategies, Portfolios, and ExecutionHandlers.
"""

from queue import Queue, Empty
from .events import MarketEvent

class EventDrivenBacktester:
    """
    Encapsulates the settings and components for carrying out
    an event-driven backtest.
    """

    def __init__(self, data_handler, execution_handler, portfolio, strategy):
        """
        Initialises the backtest.
        """
        self.data_handler = data_handler
        self.execution_handler = execution_handler
        self.portfolio = portfolio
        self.strategy = strategy
        self.events = Queue()

        self.signals = 0
        self.orders = 0
        self.fills = 0
        self.num_strats = 1

    def _run_backtest(self):
        """
        Executes the backtest.
        """
        i = 0
        while True:
            i += 1
            # Update the market bars
            if self.data_handler.continue_backtest == True:
                self.data_handler.update_bars()
            else:
                break

            # Process events
            while True:
                try:
                    event = self.events.get(False)
                except Empty:
                    break
                else:
                    if event is not None:
                        if event.type == 'MARKET':
                            self.strategy.calculate_signals(event)
                            self.portfolio.update_timeindex(event)

                        elif event.type == 'SIGNAL':
                            self.signals += 1
                            self.portfolio.update_signal(event)

                        elif event.type == 'ORDER':
                            self.orders += 1
                            self.execution_handler.execute_order(event)

                        elif event.type == 'FILL':
                            self.fills += 1
                            self.portfolio.update_fill(event)

    def simulate_trading(self):
        """
        Simulates the backtest and outputs portfolio performance.
        """
        self._run_backtest()
        self.portfolio.create_equity_curve_dataframe()

class DataHandler:
    """
    DataHandler is an abstract base class providing an interface for
    all subsequent (inherited) data handlers (both live and historic).
    """
    def get_latest_bar(self, symbol):
        raise NotImplementedError("Should implement get_latest_bar()")

    def update_bars(self):
        raise NotImplementedError("Should implement update_bars()")


class Strategy:
    """
    Strategy is an abstract base class providing an interface for
    all subsequent (inherited) strategy handling objects.
    """
    def calculate_signals(self, event):
        raise NotImplementedError("Should implement calculate_signals()")


class ExecutionHandler:
    """
    The ExecutionHandler abstract class handles the interaction
    between a set of order objects generated by a Portfolio and
    the ultimate set of Fill objects that actually occur in the
    market.
    """
    def execute_order(self, event):
        raise NotImplementedError("Should implement execute_order()")


class Portfolio:
    """
    The Portfolio class handles the positions and market
    value of all instruments at a resolution of a "bar",
    i.e. secondly, minutely, 5-min, 30-min, 60 min or EOD.
    """
    def update_signal(self, event):
        raise NotImplementedError("Should implement update_signal()")

    def update_fill(self, event):
        raise NotImplementedError("Should implement update_fill()")
